### ISSUE TITLE
Not Working Behind Proxy

### ISSUE THREAD

**Issue by jackiv** [evenup/evenup-kibana#33]
This doesn't seem to work behind a proxy.

I can use wget fine on my own from command line and my http_proxy, HTTP_PROXY, HTTPS_PROXY, https_proxy are set. However this module doesn't download kibana for me.

I have another module that downloads elasticsearch  okay.

**Comment by philipwigg** [comment]
Can you paste the log of the Puppet run? Does it try to use the proxy?

**Comment by jackiv** [comment]
Hey, thanks for replying back quickly. This can be deleted. I noticed the version of wget puppet module we were using was old enough to not have $::https_proxy in it as it does today. I updated to the current version of wget puppet module and it works.
