### ISSUE TITLE
Kibana Service Not Installed

### ISSUE THREAD

**Issue by jackiv** [evenup/evenup-kibana#34]
Hi,

Kibana was successfully downloaded and installed but the kibana service under /etc/init.d/kibana doesn't exist and as a result kibana never started. Here is the output from the install:

Debug: Exec[wget-kibana](provider=posix): Executing check 'test -s '/tmp/kibana-4.0.1-linux-x64.tar.gz''
Debug: Executing 'test -s '/tmp/kibana-4.0.1-linux-x64.tar.gz''
Debug: Exec[wget-kibana](provider=posix): Executing 'wget --no-verbose --output-document='/tmp/kibana-4.0.1-linux-x64.tar.gz' 'https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz''
Debug: Executing 'wget --no-verbose --output-document='/tmp/kibana-4.0.1-linux-x64.tar.gz' 'https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz''
Notice: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]/returns: executed successfully
Debug: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]: The container Wget::Fetch[kibana] will propagate my refresh event
Debug: Wget::Fetch[kibana]: The container Class[Kibana::Install] will propagate my refresh event
Debug: /Stage[main]/Elasticsearch::Config/File[/etc/init.d/elasticsearch]: Nothing to manage: no ensure and the resource doesn't exist
Debug: /Stage[main]/Elasticsearch::Config/File[/lib/systemd/system/elasticsearch.service]: Nothing to manage: no ensure and the resource doesn't exist
Debug: /Stage[main]/Elasticsearch::Config/File[/etc/sysconfig/elasticsearch]: Nothing to manage: no ensure and the resource doesn't exist
Info: Class[Kibana::Install]: Scheduling refresh of Class[Kibana::Service]
Debug: Class[Kibana::Install]: The container Stage[main] will propagate my refresh event
Info: Class[Kibana::Service]: Scheduling refresh of Service[kibana]
Debug: Executing '/sbin/service kibana status'
Debug: Executing '/sbin/chkconfig kibana'
Debug: Executing '/sbin/service kibana start'
Error: Could not start Service[kibana]: Execution of '/sbin/service kibana start' returned 1: 
Error: /Stage[main]/Kibana::Service/Service[kibana]/ensure: change from stopped to running failed: Could not start Service[kibana]: Execution of '/sbin/service kibana start' returned 1: 
Debug: Executing '/sbin/service kibana status'
Debug: /Stage[main]/Kibana::Service/Service[kibana]: Skipping restart; service is not running
Notice: /Stage[main]/Kibana::Service/Service[kibana]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Kibana::Service/Service[kibana]: The container Class[Kibana::Service] will propagate my refresh event
Debug: Class[Kibana::Service]: The container Stage[main] will propagate my refresh event

If I manually copy and paste the https://raw.githubusercontent.com/evenup/evenup-kibana/master/templates/kibana.legacy.service.erb to /etc/init.d/kibana, chmod 755 /etc/init.d/kibana and then rerun (after erasing what was installed from the module the first time so its like a new run) then it works (kibana is running).

Debug: Exec[wget-kibana](provider=posix): Executing check 'test -s '/tmp/kibana-4.0.1-linux-x64.tar.gz''
Debug: Executing 'test -s '/tmp/kibana-4.0.1-linux-x64.tar.gz''
Debug: Exec[wget-kibana](provider=posix): Executing 'wget --no-verbose --output-document='/tmp/kibana-4.0.1-linux-x64.tar.gz' 'https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz''
Debug: Executing 'wget --no-verbose --output-document='/tmp/kibana-4.0.1-linux-x64.tar.gz' 'https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz''
Notice: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]/returns: executed successfully
Debug: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]: The container Wget::Fetch[kibana] will propagate my refresh event
Debug: Wget::Fetch[kibana]: The container Class[Kibana::Install] will propagate my refresh event
Debug: /Stage[main]/Elasticsearch::Config/File[/etc/init.d/elasticsearch]: Nothing to manage: no ensure and the resource doesn't exist
Debug: /Stage[main]/Elasticsearch::Config/File[/lib/systemd/system/elasticsearch.service]: Nothing to manage: no ensure and the resource doesn't exist
Debug: /Stage[main]/Elasticsearch::Config/File[/etc/sysconfig/elasticsearch]: Nothing to manage: no ensure and the resource doesn't exist
Info: Class[Kibana::Install]: Scheduling refresh of Class[Kibana::Service]
Debug: Class[Kibana::Install]: The container Stage[main] will propagate my refresh event
Info: Class[Kibana::Service]: Scheduling refresh of Service[kibana]
Debug: Executing '/sbin/service kibana status'
Debug: Executing '/sbin/chkconfig kibana'
Debug: Executing '/sbin/service kibana status'
Debug: Executing '/sbin/service kibana stop'
Debug: Executing '/sbin/service kibana start'
Notice: /Stage[main]/Kibana::Service/Service[kibana]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Kibana::Service/Service[kibana]: The container Class[Kibana::Service] will propagate my refresh event
Debug: Class[Kibana::Service]: The container Stage[main] will propagate my refresh event

**Comment by philipwigg** [comment]
What Linux distribution and version are you using?

I think you might be on an EL 6 which by default still receives a systemd init script (which it can't use) unless ```$legacy_service_mode => true```.

I submitted PR https://github.com/evenup/evenup-kibana/pull/32 earlier today to detect the init system to use based on the host OS instead of having to set ```$legacy_service_mode``` so you could wait for it to be merged or use my branch.

If you don't want to do that, you can declare the class like so:-

```
class { 'kibana:
  $legacy_service_mode => true,
}
```

or add ```kibana::legacy_service_mode: true``` to your Hiera data.

Beware that if you do and my branch gets merged then my PR removes this parameter.

**Comment by philipwigg** [comment]
My PR got merged now, interested to see if using latest master resolves your issue?

**Comment by jackiv** [comment]
Thanks. I pulled it down and tried again and its still not copying the kibana script to /etc/init.d/kibana. I'm getting the same errors.

my distro version is Red Hat 4.4.7-9

**Comment by jackiv** [comment]
That works! Thanks!
When do you guys think you'll do a release with it in it?

**Comment by jlambert121** [comment]
I think @philipwigg was wanting to add some additional ubuntu support in the near future so I'd like to give him a chance to do that first.

**Comment by jackiv** [comment]
@jlambert121 okay, sounds good!

**Comment by githubgossin** [comment]
To get it to work on Ubuntu 14.04, I have to make two edits to the legacy template:
```bash
sed -i 's/\/bin\/sh$/\/bin\/bash/g' kibana.legacy.service.erb
sed -i 's/^\.\ \/etc\/rc.d\/init.d\/functions$/\.\ \/lib\/lsb\/init-functions/g' kibana.legacy.service.erb
```

**Comment by jlambert121** [comment]
@githubgossin would you want to send a PR for this?  Probably an adjustment in the params.pp can make that service adjustment.

**Comment by toepi** [comment]
this issue should be fixed with pullrequest #37 und #39?

**Comment by Mattias-** [comment]
I havn't tested this but there will still be an issue using Ubuntu right?
Since `/bin/sh` is symlinked to `dash` and not `bash`

**Comment by githubgossin** [comment]
@Mattias- I think it's ok now since the script is now POSIX compliant enough so `dash` accepts it (the problem was mostly a lot of Bash-specific if-tests which now are rewritting to be POSIX compliant so they are ok with Dash)
