### ISSUE TITLE
RHEL6 needs architecture of x86_64

### ISSUE THREAD

**Issue by billwolckenlmco** [evenup/evenup-kibana#41]
Commit 0f26ac998a5f4adb74b3b72ba0ccbffe90689c98 (pull request #38) on 7/14 adds a case statement for architecture in order to support both 32- and 64-bit Linuxes.  The problem is that it only includes "i386" and "amd64", but RHEL6 (specifically RHEL6.6 Santiago) sets $::architecture to "x86_64" which causes building the catalog to fail.  ("Error: Could not retrieve catalog from remote server: Error 400 on SERVER: No matching value for selector param 'x86_64' at /etc/puppet/environments/production/modules/kibana/manifests/install.pp:20")

**Comment by jlambert121** [comment]
@billwolckenlmco I believe #42 should resolve your issue - can you verify?

**Comment by billwolckenlmco** [comment]
#42 allowed the catalog to compile, but it installed the 32-bit version (kibana-4.0.1-linux-x86) instead of the 64-bit version.  Looking the at the updated code, the regex `/(i386|x86)/` (for the 32-bit version) would also match the string `x86_64`.  As long as the architecture fact never gets additional text (something like "i386-intel"), then anchoring the regex patterns with ^ and $ would fix it.

**Comment by billwolckenlmco** [comment]
Reopening - closed by accident.

**Comment by jlambert121** [comment]
Nice catch on the regex - updated the PR with a test for that.

**Comment by billwolckenlmco** [comment]
Thanks.  It is now working for me.
