### ISSUE TITLE
Github module code different from Puppet Forge module code

### ISSUE THREAD

**Issue by landerson61** [evenup/evenup-kibana#63]
Hi,

The code for this module in Github is different from the code in the puppet forge module. In the Github code, there are parameters for 'elasticsearch_user' and 'elasticsearch_password'.

However, if you install from the forge (puppet module install evenup-kibana), the installed module does not contain these parameters.

So, when using r10k to download this module from the forge I am unable to pass ES username & password.

**Comment by jlambert121** [comment]
2.3.0 released
