### ISSUE TITLE
kibana 4.3.0 needs small systemd change to start

### ISSUE THREAD

**Issue by mvernimmen-CG** [evenup/evenup-kibana#65]
On CentOS 7.1 Kibana 4.3.0 doesn't start logs the following in /var/log/kibana/kibana.log:
{"type":"log","@timestamp":"2015-12-01T14:03:56+00:00","tags":["fatal"],"pid":15654,"level":"fatal","message":"EACCES, open '/var/run/kibana.pid'","error":{"message":"EACCES, open '/var/run/kibana.pid'","name":"Error","stack":"Error: EACCES, open '/var/run/kibana.pid'\n    at Error (native)","code":"EACCES"}}

In other words, the kibana user doesn't (and shouldn't) have write access to /var/run
To fix this, '/usr/lib/systemd/system/kibana.service' needs to have 'RuntimeDirectory=kibana' set. But that only fixes it for systems with systemd>=211, which CentOS 7 does not have at this moment.

A workaround is to either run kibana as root (not a good idea) or to add this to kibana.service:
ExecStartPre=/usr/bin/install -o kibana -g kibana -d /var/run/kibana
PIDFile=/var/run/kibana/kibana.pid

Probably in both cases the kibana.yml needs to be set to /var/run/kibana/kibana.pid instead of the default.

**Comment by atopian** [comment]
I have a PR to fix this at evenup/evenup-kibana#67

**Comment by jlambert121** [comment]
Closed with #67
